---
    - name: Ansible remove file
      file:
        path: "/etc/yum.repos.d/rhel.repo"
        state: absent

    - name: Ansible remove file
      file:
        path: "/etc/yum.repos.d/redhat.repo"
        state: absent

    - name: Enregistrement a access red hat avec la cle d'activation
      redhat_subscription:
        state: present
        activationkey: "{{ ak_var }}"
        org_id: "{{  org_var }}"
      ignore_errors: True
